<?xml version="1.0" ?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<!DOCTYPE test [
  <!ELEMENT test (text)>
  <!ELEMENT text ANY>
  <!ATTLIST text xml:space (default|preserve) 'default'>
]>

<test>
	<text id="unspecified"> foo </text>
	<text id="default" xml:space="default"> foo </text>
	<text id="preserve" xml:space="preserve"> foo </text>
	<text id="nested">
		<text> foo </text>
		<text>;</text>
		<text xml:space="default"> bar </text>
		<text>;</text>
		<text xml:space="preserve"> baz </text>
	</text>
	<text id="nested-with-comments">
		<text> foo </text>
		<!-- comment 1 -->
		<text>;</text>
		<!-- comment 2 -->
		<text xml:space="default"> bar </text>
		<!-- comment 3 -->
		<text>;</text>
		<!-- comment 4 -->
		<text xml:space="preserve"> baz </text>
	</text>
</test>